name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install toml

      - name: Get version from pyproject.toml
        id: get_version
        run: |
          VERSION=$(python -c "import toml; print(toml.load('pyproject.toml')['project']['version'])")
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Check if tag exists
        id: check_tag
        run: |
          TAG_EXISTS=$(git tag -l "v${{ env.VERSION }}")
          if [ -z "$TAG_EXISTS" ]; then
            echo "Tag does not exist"
            echo "TAG_EXISTS=false" >> $GITHUB_ENV
          else
            echo "Tag already exists"
            echo "TAG_EXISTS=true" >> $GITHUB_ENV
          fi

      - name: Extract release notes from CHANGELOG.md
        id: extract_notes
        if: env.TAG_EXISTS == 'false'
        run: |
          VERSION=${{ env.VERSION }}
          NOTES=$(awk "/^## \[$VERSION\]/,/^## \[/{if (\$0 ~ /^## \[.*\]/) next; print}" CHANGELOG.md)
          echo "NOTES=$NOTES" >> $GITHUB_ENV

      - name: Create Release
        uses: actions/create-release@v1
        if: env.TAG_EXISTS == 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.VERSION }}
          release_name: Release ${{ env.VERSION }}
          body: ${{ env.NOTES }}
          draft: false
          prerelease: false

      - name: Skip Release
        if: env.TAG_EXISTS == 'true'
        run: echo "Skipping release creation as the tag already exists."
